#!/usr/bin/env python3
"""
Sine Look-Up Table Generator for Waveform Generator FPGA IP.

Generates a quarter-wave sine table (0 to pi/2) for use with the SineWaves.sv
module which reconstructs the full waveform using sign and direction symmetry bits.

Outputs:
  - .hex file  : One hex value per line for Verilog $readmemh
  - .coe file  : Xilinx COE format for Block RAM IP initialization
  - .mem file  : Verilog $readmemb compatible (binary, optional)

Usage:
  python coe.py [--samples N] [--bits B] [--output-dir DIR] [--format {hex,coe,both,all}]

Quarter-wave synthesis (used by SineWaves.sv):
  - Bit[31]    = sign bit      -> negate output  
  - Bit[30]    = direction bit -> mirror LUT index
  - Bit[29:21] = 9-bit LUT address (512 entries)
"""

import argparse
import math
import os
import sys
from decimal import Decimal, getcontext

# Set high precision for exact sine computation
getcontext().prec = 50


def high_precision_sin(x_float):
    """Compute sin(x) using Python's math library with double precision.
    
    For even higher accuracy, we use the Decimal module to do the
    final quantization step, avoiding floating-point rounding in the
    multiply-and-round operation.
    """
    return Decimal(str(math.sin(x_float)))


def generate_quarter_wave_lut(num_samples, num_bits):
    """Generate a quarter-wave sine LUT (0 to pi/2).
    
    Args:
        num_samples: Number of LUT entries (typically 512 for 9-bit address)
        num_bits: Bit width of each sample (typically 16)
    
    Returns:
        List of unsigned integer LUT values representing sin(0) to sin(pi/2)
    """
    max_value = Decimal(2 ** (num_bits - 1) - 1)  # e.g. 32767 for 16-bit
    lut = []
    
    for i in range(num_samples):
        # Phase spans from 0 to pi/2 (quarter wave)
        # The SineWaves module uses: addr = phase[29:21]
        # When dir=0: lut_index is used directly  (0 to pi/2)
        # When dir=1: lut_index is bit-inverted   (pi/2 to pi, mirrored)
        phase = (float(i) / float(num_samples)) * (math.pi / 2.0)
        
        sine_val = high_precision_sin(phase)
        quantized = int((sine_val * max_value).to_integral_value())
        
        # Clamp to valid range
        max_int = int(max_value)
        quantized = max(0, min(max_int, quantized))
        lut.append(quantized)
    
    return lut


def analyze_lut_quality(lut, num_bits):
    """Analyze the quality of the generated LUT."""
    max_value = 2 ** (num_bits - 1) - 1
    num_samples = len(lut)
    
    max_error = 0.0
    total_error = 0.0
    
    for i in range(num_samples):
        phase = (float(i) / float(num_samples)) * (math.pi / 2.0)
        ideal = math.sin(phase) * max_value
        actual = float(lut[i])
        error = abs(ideal - actual)
        max_error = max(max_error, error)
        total_error += error * error
    
    rms_error = math.sqrt(total_error / num_samples)
    snr_db = 20 * math.log10(max_value / rms_error) if rms_error > 0 else float('inf')
    
    print(f"LUT Quality Analysis:")
    print(f"  Samples     : {num_samples}")
    print(f"  Bit width   : {num_bits}")
    print(f"  Max value   : {max_value}")
    print(f"  Peak value  : {max(lut)}")
    print(f"  Max error   : {max_error:.4f} LSB")
    print(f"  RMS error   : {rms_error:.4f} LSB")
    print(f"  SNR         : {snr_db:.1f} dB")
    print(f"  SFDR (est)  : ~{6.02 * num_bits:.1f} dB (theoretical)")


def write_hex_file(lut, filepath, num_bits):
    """Write LUT as hex file for Verilog $readmemh."""
    hex_digits = (num_bits + 3) // 4  # Number of hex digits needed
    with open(filepath, 'w', newline='\n') as f:
        f.write(f"// Quarter-wave sine LUT: {len(lut)} samples, {num_bits}-bit\n")
        f.write(f"// Generated by coe.py for use with $readmemh\n")
        for val in lut:
            f.write(f"{val:0{hex_digits}X}\n")
    print(f"  Wrote hex file : {filepath}")


def write_coe_file(lut, filepath, num_bits):
    """Write LUT as Xilinx COE file for Block RAM IP."""
    hex_digits = (num_bits + 3) // 4
    with open(filepath, 'w', newline='\n') as f:
        f.write("; Quarter-wave sine LUT for Xilinx Block RAM IP\n")
        f.write(f"; {len(lut)} samples, {num_bits}-bit unsigned\n")
        f.write("memory_initialization_radix=16;\n")
        f.write("memory_initialization_vector=\n")
        for i, val in enumerate(lut):
            sep = ";" if i == len(lut) - 1 else ","
            f.write(f"{val:0{hex_digits}X}{sep}\n")
    print(f"  Wrote COE file : {filepath}")


def write_mem_file(lut, filepath, num_bits):
    """Write LUT as binary .mem file for Verilog $readmemb."""
    with open(filepath, 'w', newline='\n') as f:
        f.write(f"// Quarter-wave sine LUT: {len(lut)} samples, {num_bits}-bit binary\n")
        for val in lut:
            f.write(f"{val:0{num_bits}b}\n")
    print(f"  Wrote MEM file : {filepath}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate quarter-wave sine LUT for FPGA waveform generator"
    )
    parser.add_argument('--samples', type=int, default=512,
                        help='Number of LUT entries (default: 512 for 9-bit addr)')
    parser.add_argument('--bits', type=int, default=16,
                        help='Bit width per sample (default: 16)')
    parser.add_argument('--output-dir', type=str, default=None,
                        help='Output directory (default: ../../coe)')
    parser.add_argument('--format', type=str, default='both',
                        choices=['hex', 'coe', 'mem', 'both', 'all'],
                        help='Output format (default: both = hex + coe)')
    parser.add_argument('--analyze', action='store_true', default=True,
                        help='Print LUT quality analysis')
    args = parser.parse_args()
    
    if args.output_dir is None:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        args.output_dir = os.path.join(script_dir, '..', '..', 'coe')
    
    os.makedirs(args.output_dir, exist_ok=True)
    
    print(f"Generating quarter-wave sine LUT...")
    print(f"  Samples: {args.samples}, Bits: {args.bits}")
    
    lut = generate_quarter_wave_lut(args.samples, args.bits)
    
    if args.analyze:
        analyze_lut_quality(lut, args.bits)
    
    fmt = args.format
    if fmt in ('hex', 'both', 'all'):
        write_hex_file(lut, os.path.join(args.output_dir, 'sin_LUT.hex'), args.bits)
    if fmt in ('coe', 'both', 'all'):
        write_coe_file(lut, os.path.join(args.output_dir, 'sin_LUT.coe'), args.bits)
    if fmt in ('mem', 'all'):
        write_mem_file(lut, os.path.join(args.output_dir, 'sin_LUT.mem'), args.bits)
    
    print("Done.")


if __name__ == '__main__':
    main()