#ifndef WAVEGEN_REGS_H
#define WAVEGEN_REGS_H

#define WAVEGEN_BASE_ADDR   0x43C00000
#define WAVEGEN_ADDR_RANGE  0x10000

#define WAVEGEN_MODE_OFFSET     0x00
#define WAVEGEN_ENABLE_OFFSET   0x04
#define WAVEGEN_FREQ_A_OFFSET   0x08
#define WAVEGEN_FREQ_B_OFFSET   0x0C
#define WAVEGEN_AMPL_A_OFFSET   0x10
#define WAVEGEN_AMPL_B_OFFSET   0x14
#define WAVEGEN_OFFSET_A_OFFSET 0x18
#define WAVEGEN_OFFSET_B_OFFSET 0x1C
#define WAVEGEN_DCYCLE_A_OFFSET 0x20
#define WAVEGEN_DCYCLE_B_OFFSET 0x24
#define WAVEGEN_POFFSET_A_OFFSET 0x28
#define WAVEGEN_POFFSET_B_OFFSET 0x2C
#define WAVEGEN_CYCLES_A_OFFSET 0x30
#define WAVEGEN_CYCLES_B_OFFSET 0x34

#endif /* WAVEGEN_REGS_H */